version: '3.7'

services:
    rick-morty-api:
        build: ./rails/
        depends_on:
            - kafka
            - postgres
        environment:
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/
            KAFKA_SEED_BROKER: kafka:9092
        networks:
            - rick-morty-network
        ports:
            - 3001:3000
    rick-morty-transformer:
        build: ./transformer-app
        command: ["scripts/wait-for-it.sh", "kafka:9092", "--", "echo", "Kafka started"]
        depends_on:
            - kafka
            - rick-morty-api
        environment:
            KAFKA_SEED_BROKER: kafka:9092
        networks:
            - rick-morty-network
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        depends_on:
            - zookeeper
        networks:
            - rick-morty-network
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        networks:
            - rick-morty-network
        ports:
            - 5432:5432
        restart: always
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        networks:
            - rick-morty-network
        ports:
            - 2181:2181

networks:
    rick-morty-network:
        driver: bridge