# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "rickmorty_api"

development:
  <<: *common
  brokers:
    - localhost:9092

test:
  <<: *common
  brokers:
    - localhost:9092

production:
  <<: *common
  brokers:
    - kafka1.myapp.com:9092
